
name: cric_dice
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#1.0.4+5
version: 1.0.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  # dio: ^4.0.0
  # equatable: ^2.0.3
  expandable: ^5.0.1
  firebase_analytics: ^8.3.0
  firebase_core: ^1.5.0
  flutter:
    sdk: flutter
  # flutter_bloc: ^7.1.0
  flutter_html: any
  flutter_localizations:
    sdk: flutter
  # flutter_svg: ^0.21.0+1
  font_awesome_flutter: ^9.0.0
  get: ^4.1.3
  google_fonts: ^2.0.0
  http: ^0.13.3
  # image_picker: ^0.7.4
  intl: ^0.17.0
  jumping_bottom_nav_bar: ^0.1.0
  provider: ^5.0.0
  # readmore: ^2.0.0
  # supercharged: ^2.0.0
  url_launcher: ^6.0.3
  web_socket_channel: ^2.1.0
  webview_flutter: ^2.0.12
  # whatsapp_unilink: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
    - assets/images/leagues/
